'use strict';
window.ClaudianCompanion={render({local,core,issue,loading,quiet,ack,language,previewReadOnly}){
 const tr=language==='tr',t=(a,b)=>tr?b:a,e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const card=core?.cards?.[0]||(core?.focus?{title:core.focus,body:'',sourceLabel:tr?'Mevcut odak':'Current focus'}:null),item=local?.items?.[0],failed=Boolean(issue)||local?.state==='unreadable';
 const mood=quiet?'quiet':loading?'waiting':failed?'unavailable':ack?'ack':card||item?'attention':'calm';
 const title=card?.title||item?.text||(local?.state==='unconfigured'?t('A place for what matters.','Önemli olanlara bir yer.'):failed?t('I cannot reach your notes.','Notlarına ulaşamıyorum.'):t('A quiet moment.','Sakin bir an.'));
 const body=card?(card.body||t('Your current focus.','Mevcut odağın.')):(item?t('An open item from your notes.','Notlarında açık duran bir madde.'):local?.state==='unconfigured'?(previewReadOnly?t('This preview is not connected to your notes. Folder setup will open once safe migration is ready.','Bu önizleme notlarına bağlı değil. Güvenli geçiş tamamlandığında klasör kurulumu açılacak.'):t('Choose your memory folder to bring your own context here.','Kendi bağlamını burada görmek için hafıza klasörünü seç.')):failed?t('Refresh when access is available again.','Erişim sağlandığında yeniden deneyebilirsin.'):t('There is no new item to show from the available sources.','Erişilebilen kaynaklarda gösterilecek yeni bir madde yok.'));
 const button=(action,label,extra='')=>`<button data-companion-action="${action}" ${extra}>${label}</button>`;
 return `<section class="mate"><div class="mate-heading"><h1>${t('From an assistant to a companion.','Bir asistandan, yol arkadaşına.')}</h1><span class="development-label">${t('In development','Geliştiriliyor')}</span></div><div class="mate-stage"><div class="mate-presence" data-mood="${mood}" aria-hidden="true"><div class="mate-face"><div class="mate-eyes"><i></i><i></i></div><div class="mate-mouth"></div></div><div class="mate-foot"></div></div><article class="mate-message" aria-live="polite"><h2>${e(title)}</h2><p class="mate-state" role="status">${loading?t('Refreshing…','Yenileniyor…'):ack?e(ack):quiet?t('Motion paused','Hareket duraklatıldı'):failed?t('Access needs attention','Erişim sorunu var'):card?t('For you','Senin için'):item?t('From your notes','Notlarından'):t('Here when needed','Gerektiğinde burada')}</p><p>${e(body)}</p>${issue?`<p role="alert">${e(issue)}</p>`:''}${item&&!card?`<div class="mate-actions">${button('source',t('Open note','Notu aç'),`data-id="${e(item.id)}"`)}${button('later',t('In an hour','Bir saat sonra'),`data-id="${e(item.id)}"`)}${button('dismiss',t('Hide','Gizle'),`data-id="${e(item.id)}"`)}</div><p class="mate-fine">${t('Hiding a cue leaves the task and note unchanged.','Gizlemek görevi tamamlamaz; notun olduğu gibi kalır.')}</p>`:''}</article></div><div class="mate-bottom"><p>${e(card?.sourceLabel||item?.source||t('Only available context is shown.','Yalnız erişilebilen bağlam gösterilir.'))}</p><div>${button('quiet',quiet?t('Resume motion','Hareketi aç'):t('Pause motion','Hareketi duraklat'),`aria-pressed="${quiet}"`)}${button('refresh',t('Refresh','Yenile'),loading?'disabled':'')}</div></div><details class="mate-details"><summary>${t('Sources and connection','Kaynaklar ve bağlantı')}</summary><p>${t('Local notes are a limited starting point. The companion’s contextual reasoning is still in development.','Yerel notlar sınırlı bir başlangıç kaynağıdır. Yol arkadaşının bağlam değerlendirmesi geliştiriliyor.')}</p><p>${e(local?.vault||t('No memory folder selected.','Hafıza klasörü seçilmedi.'))}</p>${previewReadOnly?`<p>${t('Account connection is closed in this development preview.','Bu geliştirme önizlemesinde hesap bağlantısı kapalı.')}</p>`:!core?`<form id="mate-core-form"><label for="mate-code">${t('Existing Core access code','Mevcut Core erişim kodu')}</label><input id="mate-code" type="password" maxlength="128" required autocomplete="off"><button type="submit">${t('Connect','Bağlan')}</button></form>`:button('disconnect',t('Disconnect Core','Core bağlantısını kes'))}</details></section>`;
},mount(container,onAction){container.querySelectorAll('[data-companion-action]').forEach(b=>b.addEventListener('click',()=>onAction(b.dataset.companionAction,b.dataset.id)));container.querySelector('#mate-core-form')?.addEventListener('submit',ev=>{ev.preventDefault();onAction('connect',container.querySelector('#mate-code').value);});}};
